---
name: Factions
version: 2.0.4
main: ConstructStudios\Factions\Loader
description: "Custom factions factions plugin designed by ConstructStudios"
author: ConstructStudios
api: 3.0.0
commands:
  faction:
    description: "Faction main command"
    permission: revofactions.command.use
    aliases: ["f"]
permissions:
  revofactions.command.use:
    default: true
    description: "Allows to use /faction"

...